### ISSUE TITLE
How to run WebTestClient test with debugger 

### ISSUE THREAD

**Issue by andreykirson** [PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-2E#2]
Could you tell me how to run the WebTestClient test with the debugger? I mean if I want to debug RecommendationServiceImpl while running the test I put a stop point in the getRecommendationByProductId() test and in RecommendationServiceImpl, but when the test is run it does not go to RecommendationServiceImpl and I can not see how it works.   

![image](https://user-images.githubusercontent.com/32255911/133196115-ef6f2088-8d64-4b4c-b1eb-e024aa0dffcd.png)
![image](https://user-images.githubusercontent.com/32255911/133196526-70ead5ba-6607-43e3-9127-b46eb3cb9802.png)

**Comment by magnus-larsson** [comment]
Hello Andrey and thanks for reporting this issue!

I tried running the test in the debugger, using IntelliJ 2021.2, and the execution stopped at the breakpoint in the getRecommendations method as shown in this screenshot:

<img width="1521" alt="Screenshot 2021-09-14 at 08 02 21" src="https://user-images.githubusercontent.com/1313727/133203600-ec2bd7a5-7505-4ecb-b048-5868e6f4cf56.png">

From looking at your screenshot it seems like your breakpoint is set inside the if statement for negative productIds. Since the productId is set to 1 in this test, your breakpoint will never be reached and therefore the debugger will not stop the execution.

Could that be the reason?

Will the debugger stop on a breakpoint set on the If statement (as shown in my screenshot)?

**Comment by andreykirson** [comment]
Hi, Larsoon. 
Thanks a lot for the operative answer. Yeah, you are right just changing the stop point helped fix it.
